@HotelListing.api_HostAddress = https://localhost:7027


GET {{HotelListing.api_HostAddress}}/api/hotels

###

POST {{HotelListing.api_HostAddress}}/api/hotels
Content-Type: application/json

{
  "id": 4,
  "name": "best 2",
  "adress": "amman",
  "ratting": "4.5"
}

###

@id=4
DELETE {{HotelListing.api_HostAddress}}/api/hotels/{{id}}

###

GET {{HotelListing.api_HostAddress}}/api/hotels/{{id}}

###

PUT {{HotelListing.api_HostAddress}}/api/hotels/{{id}}
Content-Type: application/json

{
  "id": 1,
  "name": "joo",
  "adress": "amman",
  "ratting": "4.5"
}

###
